config/routes.rb
HbbnextIdm::Application.routes.draw do

  get "welcome/index"

  get 'admin', to: 'admin#index',    as: 'admin'
  get "admin/index"

  get 'signup', to: 'consumers#new',    as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :consumers

  resources :swagger

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
    end
    namespace :v2 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
      resources :contexts do
        namespace :active do
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :devices, only: [:index, :create, :show, :update, :destroy]
          resources :udrs, only: [:index, :create, :show, :update, :destroy]
        end
        get 'active'
      end
    end
    namespace :v3 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
      resources :contexts do
        namespace :active do
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :devices, only: [:index, :create, :show, :update, :destroy]
          resources :udrs, only: [:index, :create, :show, :update, :destroy]
        end
        get 'active'
      end
    end
  end

  resources :users

  resources :devices

  resources :contexts

  resources :contexts do
    namespace :active do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :devices, only: [:index, :create, :show, :update, :destroy]
      resources :udrs, only: [:index, :create, :show, :update, :destroy]
    end
    get 'active'
  end

  get 'wiki', to: 'wiki#index',    as: 'wiki'
  get "wiki/index"

  root :to => 'welcome#index'

end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :address, :alias, :display_name, :udr_ids, :user_ids, :uniqueid
  attr_protected :uuid, :created_by

  has_many :udrs, :dependent => :destroy
  has_many :users, :through => :udrs

  accepts_nested_attributes_for :udrs
end

app/controllers/active/devices_controller.rb
module Active
  class DevicesController < ApplicationController    
    
    # GET /contexts/1/active/devices
    def index
      @context = Context.find(params[:context_id])
    end
    
    # GET /contexts/1/active/devices/2
    def show
      head :forbidden
    end
    
    # POST /contexts/1/active/devices
    def create
      head :forbidden
    end
    
    # PUT /contexts/1/active/devices/2
    def update
      head :forbidden
    end
    
    # DELETE /contexts/1/active/devices/2
    def destroy
      head :forbidden
    end
  end 
end

app/controllers/api/v1/devices_controller.rb
module Api
  module V1
    class DevicesController < ApplicationController
      before_filter :restrict_access
      respond_to :json
      
      # GET /devices.json
      def index
      	@devices = Device.all
        respond_with @devices
      end
      
      # GET /devices/1.json
      def show
        @device = Device.find(params[:id])

        @cids = []
        @device.udrs.each do |udr|
          udr.contexts.each do |context|
            @cids.push(context.id)
          end
        end

        respond_with @device, @cids
      end
      
      # POST /devices.json
      def create
      #  @device = Device.create(params[:device])
      #  respond_with @device
        head :forbidden
      end
      
      # PUT /devices/1.json
      def update
      #  @device = Device.update(params[:id], params[:devices])
      #  respond_with @device
        head :forbidden
      end
      
      # DELETE /devices/1.json
      def destroy
      #  @device = Device.destroy(params[:id])
      #  respond_with @device
        head :forbidden
      end
      
      private
        def restrict_access
          api_key = Consumer.find_by_access_token(params[:access_token])
          head :unauthorized unless api_key
        end
    end
  end
end

app/controllers/api/v1/resources/devices_controller.rb
module Api
  module V1
  	module Resources
	  class DevicesController < ApplicationController
		respond_to :json

		# GET /users.json
		def index
		end
	  end
	end
  end
end

app/controllers/api/v2/devices_controller.rb
module Api
  module V2
    class DevicesController < ApplicationController
      before_filter :restrict_access
      respond_to :json

      # GET /devices.json
      def index
      	@devices = Device.all
        respond_with @devices
      end

      # GET /devices/1.json
      def show
        @device = Device.find(params[:id])

        @cids = []
        @device.udrs.each do |udr|
          udr.contexts.each do |context|
            @cids.push(context.id)
          end
        end

        respond_with @device, @cids
      end

      # POST /devices.json
      def create
        @device = Device.new(params[:device])
        @device.uuid = SecureRandom.uuid
        current_consumer ||= Consumer.find_by_access_token(params[:access_token])
        @device.created_by = current_consumer.email
        if @device.save
          set_udr_name
          respond_with @device, status: :created, location: @device
        else
          render json: @device.errors, status: :unprocessable_entity
        end
      end

      # PUT /devices/1.json
      def update
        @device = Device.find(params[:id])
        if @device.update_attributes(params[:device])
          if not @device.created_by
            current_consumer ||= Consumer.find_by_access_token(params[:access_token])
            @device.created_by = current_consumer.email
          end
          set_udr_name
        end
        respond_with @device
      end

      # DELETE /devices/1.json
      def destroy
        @device = Device.destroy(params[:id])
        respond_with @device
      end

      private
        def restrict_access
          api_key = Consumer.find_by_access_token(params[:access_token])
          head :unauthorized unless api_key
        end
        def set_udr_name
          @device.udrs.each do |udr|
            @device.attributes = {
              :udrs_attributes => [
                { :id => udr.id,
                  :name => "#{@device.users.find(udr.user_id).username}:#{@device.display_name}",
                  :role_id => 4
                }
              ]
            }
            if not udr.uuid
              udr.uuid = SecureRandom.uuid
            end
            if not udr.created_by
              current_consumer ||= Consumer.find_by_access_token(params[:access_token])
              udr.created_by = current_consumer.email
            end
          end
          @device.update_attributes(params[:device])
        end
    end
  end
end

app/controllers/api/v2/resources/devices_controller.rb
module Api
  module V2
  	module Resources
	  class DevicesController < ApplicationController
		respond_to :json

		# GET /users.json
		def index
		end
	  end
	end
  end
end

app/controllers/api/v3/active/devices_controller.rb
module Api
  module V3
    module Active
      class DevicesController < ApplicationController

        # GET /contexts/1/active/devices
        def index
          @context = Context.find(params[:context_id])
        end

        # GET /contexts/1/active/devices/2
        def show
          head :forbidden
        end

        # POST /contexts/1/active/devices
        def create
          head :forbidden
        end

        # PUT /contexts/1/active/devices/2
        def update
          head :forbidden
        end

        # DELETE /contexts/1/active/devices/2
        def destroy
          head :forbidden
        end
      end
    end
  end
end

app/controllers/api/v3/devices_controller.rb
module Api
  module V3
    class DevicesController < ApplicationController
      before_filter :restrict_access
      respond_to :json

      # GET /devices.json
      def index
      	@devices = Device.all
        respond_with @devices
      end

      # GET /devices/1.json
      def show
        @device = Device.find(params[:id])

        @cids = []
        @device.udrs.each do |udr|
          udr.contexts.each do |context|
            @cids.push(context.id)
          end
        end

        respond_with @device, @cids
      end

      # POST /devices.json
      def create
        @device = Device.new(params[:device])
        @device.uuid = SecureRandom.uuid
        current_consumer ||= Consumer.find_by_access_token(params[:access_token])
        @device.created_by = current_consumer.email
        if @device.save
          set_udr_name
          respond_with @device, status: :created, location: @device
        else
          render json: @device.errors, status: :unprocessable_entity
        end
      end

      # PUT /devices/1.json
      def update
        @device = Device.find(params[:id])
        if @device.update_attributes(params[:device])
          if not @device.created_by
            current_consumer ||= Consumer.find_by_access_token(params[:access_token])
            @device.created_by = current_consumer.email
          end
          set_udr_name
        end
        respond_with @device
      end

      # DELETE /devices/1.json
      def destroy
        @device = Device.destroy(params[:id])
        respond_with @device
      end

      private
        def restrict_access
          api_key = Consumer.find_by_access_token(params[:access_token])
          head :unauthorized unless api_key
        end
        def set_udr_name
          @device.udrs.each do |udr|
            @device.attributes = {
              :udrs_attributes => [
                { :id => udr.id,
                  :name => "#{@device.users.find(udr.user_id).username}:#{@device.display_name}",
                  :role_id => 4
                }
              ]
            }
            if not udr.uuid
              udr.uuid = SecureRandom.uuid
            end
            if not udr.created_by
              current_consumer ||= Consumer.find_by_access_token(params[:access_token])
              udr.created_by = current_consumer.email
            end
          end
          @device.update_attributes(params[:device])
        end
    end
  end
end

app/controllers/api/v3/resources/devices_controller.rb
module Api
  module V3
  	module Resources
	  class DevicesController < ApplicationController
		respond_to :json

		# GET /users.json
		def index
		end
	  end
	end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  before_filter :authorize, only: [:new, :create, :edit, :update, :destroy]

  # GET /devices
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /devices/1
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /devices/new
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  def create
    @device = Device.new(params[:device])

    require 'securerandom'
    @device.uuid = SecureRandom.uuid

    @device.created_by = current_consumer.email

    respond_to do |format|
      if @device.save
        set_udr_name
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /devices/1
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        if not @device.created_by
          @device.created_by = current_consumer.email
        end
        set_udr_name
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /devices/1
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
    end
  end

  private
    def set_udr_name
      @device.udrs.each do |udr|
        @device.attributes = {
          :udrs_attributes => [
            { :id => udr.id,
              :name => "#{@device.users.find(udr.user_id).username}:#{@device.display_name}",
              :role_id => 4
            }
          ]
        }
        if not udr.uuid
          udr.uuid = SecureRandom.uuid
        end
        if not udr.created_by
          udr.created_by = current_consumer.email
        end
      end
      @device.update_attributes(params[:device])
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_devicecontexts.html.erb
<% cnames = [] %>
<% device.udrs.each do |udr| %>
	<% udr.contexts.each do |context| %>
		<% cnames.push(context.display_name) %>
	<% end %>
<% end %>
<% cnames.uniq.each do |cn| %>
	<%= cn %>
<% end %>

app/views/devices/_deviceusers.html.erb
<% device.users.each do |user| %>
	<% device.udrs.each do |udr| %>
		<% if udr.user_id == user.id %>
			<% if udr.role_id == 1 %>
	    		<b><%= user.username %></b>
	    		(<%= user.roles.find(udr.role_id).name %>)
	    	<% else %>
	    		<%= user.username %>
	    		(<%= user.roles.find(udr.role_id).name %>)
    		<% end %>
    	<% end %>
    <% end %>
<% end %>

app/views/devices/_form.html.erb
<%= semantic_form_for @device, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.inputs do %>
    <%= f.input :alias, :label => "Alias" %>
    <%= f.input :display_name, :label => "Display-Name" %>
    <%= f.input :address, :label => "Address" %>
    <%= f.input :uniqueid, :label => "Unique ID" %>
    <%= render "formusers", :f => f %>
  <% end %>

  <%= f.actions :class => 'form-actions' do %>
    <%= f.action :submit, :as => :input, :button_html => { :class => 'btn btn-primary' } %>
    <%= link_to 'Back', devices_path, :class => 'btn' %>
  <% end %>
<% end %>

app/views/devices/_formroles.html.erb
<div id="formroles" class="radios" style="display:none">
<%= f.semantic_fields_for :udrs do |d| %>
   <%= d.inputs :user, :role, :as => "select" %>
<% end%>
</div>

app/views/devices/_formusers.html.erb
<div id="formusers" class="radios">
	<%= f.input :users, :label => "Users" %>
</div>

app/views/devices/_radios.html.erb
<script type="text/javascript"charset="UTF-8">
	$(document).ready(function(){ 
		$("input[name$='edit']").click(function() {
			var tmp = $(this).val();
			$("div.radios").hide();
			$("#"+tmp).show();
		}); 
	});
</script>
<p>
	Edit:<br />
	<div id="radios">
		<input type="radio" name="edit" value="formusers" checked> Users<br />
		<input type="radio" name="edit" value="formroles"> Roles<br />
	</div>
</p>

app/views/devices/edit.html.erb
<h2>Editing device</h2>

<%= render 'form' %>

app/views/devices/index.html.erb
<h2>Devices</h2>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Alias</th>
    <th>Display-Name</th>
    <th>Address</th>
    <th>Users</th>
    <th>Contexts</th>
    <th>Actions</th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= link_to device.id, device %></td>
    <td><%= device.alias %></td>
    <td><%= device.display_name %></td>
    <td><%= device.address %></td>
    <td>
        <%= render :partial => "deviceusers", :locals => { :device => device } %>
    </td>
    <td>
        <%= render :partial => "devicecontexts", :locals => { :device => device } %>
    </td>
    
    <td><%= link_to "API", api_v3_device_path(device, :access_token => if defined?(current_consumer.access_token) then current_consumer.access_token end), :class => 'btn btn-mini' %>
        <%= link_to 'Edit', edit_device_path(device), :class => 'btn btn-mini' %>
    <%= link_to 'Delete', device, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path, :class => 'btn btn-primary' %>

app/views/devices/new.html.erb
<h2>New device</h2>

<%= render 'form' %>

app/views/devices/show.html.erb
<h2>Details of Device #<%= @device.id %></h2>

<p id="notice"><%= notice %></p>

<p>
  <b>Alias:</b>
  <%= @device.alias %>
</p>

<p>
  <b>Display name:</b>
  <%= @device.display_name %>
</p>

<p>
  <b>UUID:</b>
  <%= @device.uuid %>
</p>

<p>
  <b>Address:</b>
  <%= @device.address %>
</p>

<p>
  <b>Users:</b>
  <%= render :partial => "deviceusers", :locals => { :device => @device } %>
</p>

<p>
  <b>Contexts:</b>
  <%= render :partial => "devicecontexts", :locals => { :device => @device } %>
</p>

<p>
  <b><em>Created by:</em></b>
  <em><%= @device.created_by %></em>
</p>

<p>
  <b>Unique ID:</b>
  <%= @device.uniqueid %>
</p>

<div class="form-actions">
  <%= link_to 'Edit', edit_device_path(@device), :class => 'btn' %>
  <%= link_to 'Back', devices_path, :class => 'btn' %>
</div>