config/routes.rb
HbbnextIdm::Application.routes.draw do

  get "welcome/index"

  get 'admin', to: 'admin#index',    as: 'admin'
  get "admin/index"

  get 'signup', to: 'consumers#new',    as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :consumers

  resources :swagger

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
    end
    namespace :v2 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
      resources :contexts do
        namespace :active do
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :devices, only: [:index, :create, :show, :update, :destroy]
          resources :udrs, only: [:index, :create, :show, :update, :destroy]
        end
        get 'active'
      end
    end
    namespace :v3 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
      resources :contexts do
        namespace :active do
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :devices, only: [:index, :create, :show, :update, :destroy]
          resources :udrs, only: [:index, :create, :show, :update, :destroy]
        end
        get 'active'
      end
    end
  end

  resources :users

  resources :devices

  resources :contexts

  resources :contexts do
    namespace :active do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :devices, only: [:index, :create, :show, :update, :destroy]
      resources :udrs, only: [:index, :create, :show, :update, :destroy]
    end
    get 'active'
  end

  get 'wiki', to: 'wiki#index',    as: 'wiki'
  get "wiki/index"

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h2>Welcome</h2>

<p>Welcome to the <a href="http://www.hbb-next.eu">HBB-Next</a> Identity Management solution implemented by <a href="http://www.telekom.sk">Slovak Telekom</a>.</p>

<p>Please feel free to browse the resources at the top of this page.</p>

<p>The project provides the following information:
	<ul>
		<li><%= link_to 'API access', swagger_index_url %></li>
		<li>Swagger resource description</li>
		<ul>
			<li><%= link_to 'Resources', api_v3_resources_url %></li>
			<li><%= link_to 'Users', api_v3_resources_users_url %></li>
			<li><%= link_to 'Devices', api_v3_resources_devices_url %></li>
			<li><%= link_to 'Contexts', api_v3_resources_contexts_url %></li>
		</ul>
		<li><%= link_to 'Wiki', wiki_index_url %></li>
	</ul>
</p>

<p>In case of questions, problems, or ideas please contact:
	<address>
		<strong>Sebastian Schumann</strong><br />
		<i class="icon-envelope"></i>&nbsp<a href="mailto:seb.schumann@gmail.com">seb.schumann@gmail.com</a><br />
		<i class="icon-phone-sign"></i>&nbsp;+421&nbsp;903&nbsp;419&nbsp;345
	</address>
</p>