config/routes.rb
HbbnextIdm::Application.routes.draw do

  get "welcome/index"

  get 'admin', to: 'admin#index',    as: 'admin'
  get "admin/index"

  get 'signup', to: 'consumers#new',    as: 'signup'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :consumers

  resources :swagger

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
    end
    namespace :v2 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
      resources :contexts do
        namespace :active do
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :devices, only: [:index, :create, :show, :update, :destroy]
          resources :udrs, only: [:index, :create, :show, :update, :destroy]
        end
        get 'active'
      end
    end
    namespace :v3 do
      resources :users
      resources :devices
      resources :contexts
      get 'resources/resources', to: 'resources#index', as: 'resources'
      get 'resources', to: 'resources#index', as: 'resources'
      get 'resources/users', to: 'resources/users#index', as: 'resources/users'
      get 'resources/devices', to: 'resources/devices#index', as: 'resources/devices'
      get 'resources/contexts', to: 'resources/contexts#index', as: 'resources/contexts'
      resources :contexts do
        namespace :active do
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :devices, only: [:index, :create, :show, :update, :destroy]
          resources :udrs, only: [:index, :create, :show, :update, :destroy]
        end
        get 'active'
      end
    end
  end

  resources :users

  resources :devices

  resources :contexts

  resources :contexts do
    namespace :active do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :devices, only: [:index, :create, :show, :update, :destroy]
      resources :udrs, only: [:index, :create, :show, :update, :destroy]
    end
    get 'active'
  end

  get 'wiki', to: 'wiki#index',    as: 'wiki'
  get "wiki/index"

  root :to => 'welcome#index'

end

app/views/layouts/_footer.html.erb
<hr />
<p class="muted">
	&copy; Slovak Telekom, 2012-<%= Date.today.year %>
</p>
<p class="muted">
	<small>
		Deployed at: <%= $currentTime %><br />
		API version: <%= $currentVersion %><br />
		Release (tag): <%= $currentRelease %>
	</small>
</p>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#"><%= image_tag("hbbnext.png", :alt => "HBB-Next logo", :size => "52x20") %> IdM</a>
      <div class="nav-collapse">
        <ul class="nav">
          <%= nav_link 'Home', root_path %>
          <%= nav_link 'Users', users_path %>
          <%= nav_link 'Devices', devices_path %>
          <%= nav_link 'Contexts', contexts_path %>
          <% if current_consumer %>
            <%= nav_link 'Administration', admin_path %>
          <% end %>
        </ul>
      </div>
      <a class="navbar-search pull-right" href="http://www.telekom.sk"><%= image_tag("st.jpg", :alt => "ST", :size => "84x27") %></a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HBB-Next Identity Management</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <link href="/favicon.ico" rel="icon" type="image/x-icon" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render "layouts/navigation" %>

	<div class="container">
		<div class="row">
			<div class="span7">
				<h1>HBB-Next Identity Management</h1>
			</div>
			<div class="span5">
				<% if current_consumer %>
					<p class="alert alert-success">
						Logged in as <%= current_consumer.email %><br />
						Access token: <%= current_consumer.access_token %><br />
						<%= link_to "Log out", logout_path %>
					</p>
				<% else %>
					<p class="alert alert-info">
						<%= link_to "Sign up", signup_path %>  and <%= link_to "log in", login_path %> to edit and delete resources and use the API.
					</p>
				<% end %>
			</div>
		</div>
	
		<%= yield %>
		
		<%= render "layouts/footer" %>
	
	</div>
	
</body>
</html>